// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM8J4aDICM3OlvJbHqd752_bm1i93B7oU',
    appId: '1:744628010568:web:2109d70cb530b3236b627d',
    messagingSenderId: '744628010568',
    projectId: 'rajyotsava-ee997',
    authDomain: 'rajyotsava-ee997.firebaseapp.com',
    storageBucket: 'rajyotsava-ee997.appspot.com',
    measurementId: 'G-4R3S7H1WR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC13Ck2YKo3xe5ez8SrH7tHUTp5VxHIg5w',
    appId: '1:744628010568:android:8a421312cecbdcb46b627d',
    messagingSenderId: '744628010568',
    projectId: 'rajyotsava-ee997',
    storageBucket: 'rajyotsava-ee997.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVLQFJF19YTWbGP15XN7eD1d2nCMFYgiE',
    appId: '1:744628010568:ios:54b14c00d0091c806b627d',
    messagingSenderId: '744628010568',
    projectId: 'rajyotsava-ee997',
    storageBucket: 'rajyotsava-ee997.appspot.com',
    iosBundleId: 'pes.edu.rajyotsava',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVLQFJF19YTWbGP15XN7eD1d2nCMFYgiE',
    appId: '1:744628010568:ios:675f1877bcca671f6b627d',
    messagingSenderId: '744628010568',
    projectId: 'rajyotsava-ee997',
    storageBucket: 'rajyotsava-ee997.appspot.com',
    iosBundleId: 'pes.edu.rajyotsava.RunnerTests',
  );
}
